### ISSUE TITLE
Lexical syntax: Identifiers and Numbers

### ISSUE THREAD

**Issue by mnieper** [pre-srfi/static-scheme#26]
In Scheme, the lexical syntax for identifiers is rather complicated in order to allow identifiers like `+` or `->` that begin like numbers.

For Steme's native (!) lexical syntax (which can be a further development of Scheme's lexical syntax), we have the option to streamline a few things concerning the lexical syntax of identifiers and numbers. I would like to discuss the following options:

1. Numbers and identifiers are described using the same grammar. Everything of that syntax that isn't a number is automatically lexed as an identifier. Under this proposal, we don't need special rules for `+`, for example. Things like `1+` would become identifiers.

2. Get rid of identifiers that begin like numbers. This would, in particular, remove `+` and `-`. While this simplifies the specification quite a bit, this would make arithmetic formulas look more alien, e.g. like `(n+ 3 (n* 2 10))`, where I used the prefix `n` for iNteger. (Following Bourbaki's notation ℤ for the integers, a prefix `z` for Zahlen would also be sensible.)

3. Parse identifiers as in R7RS, which means to include a number of peculiar lexing rules.

4. Add a prefix to all numbers, e.g. `#`.

**Comment by arvyy** [comment]
What is the intent of the change? From user POV, I find scheme's way of number syntax quite intuitive, and change of it would be a break of principle of least surprise IMO (especially with steme's premise "looks and feels like Scheme"). From compiler implementation POV, I don't have too much experience, but I'd imagine keeping same lexical syntax would make life simpler, because then existing scheme lexers could be reused without having to create and maintain new one for steme.

**Comment by mnieper** [comment]
Well, Steme can certainly have more than one reader. A Steme program could be written with RnRS lexical syntax or, more generally, represented as a Scheme datum. This does not preclude a further development of the RnRS syntax (which hasn't stayed entirely stable between the various RnRS), which is why I spoke about Steme's _native_ syntax.

While Scheme has clear semantics, the lexical representation of its datums is not very regular. This is not a problem for the implementer (you have to write a lexer only once) but it becomes a problem when we want to extend the lexical syntax later (by subspecifications or through possible reader macros). Such extensions work the better the more uniform the syntax to be extended is.

I didn't write it but I have, of course, personal preferences for the options above but I didn't want to bias the discussion.

**Comment by lassik** [comment]
FWIW, I'd favor specifying the syntax tree (i.e. datum objects) and not worry about read syntax until the end. We shouldn't introduce new read syntax that's not in RnRS. Slight variations on RnRS may be ok as long as there always exists a both-ways compatible syntax for writing everything.

IMHO reader macros should be gradually deprecated and not introduced into new languages. The syntaxes of existing languages like C++, Rust, and Haskell are already bursting at the seams, and Lisps are slowly following suit. It's clear that we need to get out of text macros and into structural macros with a themeable representation; it's the only sustainable path forward.

**Comment by lassik** [comment]
(Offtopic: Does the `Z` math notation come from the word Zahlen BTW? :) How old is the notation?)

**Comment by lassik** [comment]
From a language design point-of-view, a visual macro in the UI can be represented by a Scheme macro in the language. The theming language can be separate and orthogonal. The main thing would be to keep out reader macros so as not to complicate parsing.

**Comment by mnieper** [comment]
> 
> 
> (Offtopic: Does the `Z` math notation come from the word Zahlen BTW? :) How old is the notation?)

Offtopic: Yes, it does. The words "Zahlen" (numbers) to "zählen" (to count) have the same root as English "tale" but have undergone the High German consonant shift. (NB: In Lower Geman, it is still "Tahl".)

As far as I know, the letter Z was popularized by the French group of Bourbaki in the first half of the 20th century. At that time, a lot of import number theory papers had been written in German so they were certainly aware of the word _Zahlen_.

**Comment by mnieper** [comment]
> 
> 
> FWIW, I'd favor specifying the syntax tree (i.e. datum objects) and not worry about read syntax until the end. We shouldn't introduce new read syntax that's not in RnRS. Slight variations on RnRS may be ok as long as there always exists a both-ways compatible syntax for writing everything.
> 
> IMHO reader macros should be gradually deprecated and not introduced into new languages. The syntaxes of existing languages like C++, Rust, and Haskell are already bursting at the seams, and Lisps are slowly following suit. It's clear that we need to get out of text macros and into structural macros with a themeable representation; it's the only sustainable path forward.

This is not the way we go with R7RS (large). Quite a number of new lexical syntax has been showing up complicating the reader further. And it cannot be reduced to some primitive lexical syntax akin to how most Scheme special forms can be reduced to primitive syntax through the use of macros.

While I do not want to say that we need reader macros if they worked on a uniform core of Steme's lexical syntax and would extend that core only in a uniform way, the situation would be much better than we have in R7RS (large).

Note that the intend of this thread is to discuss not how to complicate parsing (by a human or the computer) but how to make it simpler by making it more uniform. I have already convinced myself that, for Steme, we do not need dotted lists and we probably also do not need to embed literal vectors in source code.

**Comment by lassik** [comment]
A tentative but happy +1 from me on lack of dotted lists. I have some WIP code for Vector Scheme, a variant of Scheme that has only vectors, no pairs. Even the syntax tree is made of vectors; the read syntax `(foo 1 2 3)` makes a vector.

The R7RS-large read syntax proposals in the [lexical docket](https://github.com/johnwcowan/r7rs-work/blob/master/LexicalDocket.md) are mostly conservative stuff about keywords and different kinds of vectors. (Not counting the radically different stuff like whitespace-based scoping and such, which is unlikely to make it.) These are minor variations on existint syntax that  don't get into the really problematic territory that e.g. the CL programmable reader lets people do - remap the entire syntax if they like.

**Comment by mnieper** [comment]
> A tentative but happy +1 from me on lack of dotted lists. I have some WIP code for Vector Scheme, a variant of Scheme that has only vectors, no pairs. Even the syntax tree is made of vectors; the read syntax `(foo 1 2 3)` makes a vector.

For source code, vectors instead of lists to build the tree structure seem like a viable approach, but what if the code needs proper lists (e.g. for O(1) extension)?

**Comment by johnwcowan** [comment]
> 1. Numbers and identifiers are described using the same grammar. Everything of that syntax that isn't a number is automatically lexed as an identifier. Under this proposal, we don't need special rules for `+`, for example. Things like `1+` would become identifiers.

The trouble with that is that it leaves no space for new kinds of numerals such as "3in" (a quantity with a unit, already present in Kawa) or `3π+4` (a restricted kind of irrational).  Currently these are not valid identifiers: they are what CL calls potential numbers.  (Nonetheless, many Schemes do exactly this already.)

> 2. Get rid of identifiers that begin like numbers. This would, in particular, remove `+` and `-`. While this simplifies the specification quite a bit, this would make arithmetic formulas look more alien, e.g. like `(n+ 3 (n* 2 10))`, where I used the prefix `n` for iNteger. (Following Bourbaki's notation ℤ for the integers, a prefix `z` for Zahlen would also be sensible.)

Currently R[56]RS and R7RS are different: the former require that the first character of an identifier cannot be a valid first character for any number (except for the peculiar identifiers).  This seemed to WG1 to be too restrictive, so we changed it to require that the initial prefix of an identifier not be identifiable as a number: this allows `.foo` and `+foo+` as identifiers but not the examples above.

> 3. Parse identifiers as in R7RS, which means to include a number of peculiar lexing rules.

They are hard to state in a BNF-style notation, but intuitively they are easy to understand, and keeping them the same as Scheme satisfies the "looks like Scheme" goal.   I would not object to an extension like `#s(constructor name value name value )` for a typed constant.

> 4. Add a prefix to all numbers, e.g. `#`.

Feh.

The reason for keeping all lexical issues segregated is so that implementers will only have to change their readers once.  I doubt if many of these will make it past WG2.

I agree that dotted pairs are not a Good Thing.  I suppose the compiler could notice that calls on `vector` have constants and compile them to a vector literal.

OT: In English we still *tell time* 'count the hours', we have *tellers* who count money at a bank or votes at an election, something *tells against* you if it counts against you, and we have the idiom *all told*, originally meaning 'all counted' but now 'all things considered'.  *Tally* 'count' is similar but is of French/Latin origin; however, it's possible that Late Latin borrowed it from Proto-Germanic (we know of many borrowings in both directions).

**Comment by mnieper** [comment]
So the resolution seems to be not to modify Scheme's lexical syntax (which includes extending it by interpreting everything as an identifier than cannot be parsed as something else) or to develop it further, but just to take a (well-defined) subset of the existing lexical syntax (e.g. a restriction to proper lists or not supporting the vector syntax) for Steme.

Therefore, I am closing this issue. Reopen it if necessary.
