### ISSUE TITLE
Gradual Typing

### ISSUE THREAD

**Issue by aijony** [pre-srfi/static-scheme#5]
> FFI: Scheme is the FFI of Steme. In order to call a Scheme procedure, the programmer must certify that it is pure and what type it returns. Such certifications can be global or local.

I think this is on the right track and especially for true FFI (C from Steme).

However, I think by default all untyped scheme variables should have the type `Any`, and we can always have an unsafe escape hatch. For example, this returns type `Bar`: `((unsafe: foo (-> Bar Bar)) bar)` where `foo` is untyped and `bar` is type Bar.

The other question is calling typed scheme from untyped scheme. We will need to type check at run-time which will be a performance hit that users of gradually typed languages sometimes complain about. We could again have an escape hatch `(unsafe-call bar foo)` where `bar` is typed and `foo`  is untyped. However, if the typed scheme optimized typed code by unboxing variables, this could not only result in type unsoundness but gross type unsafe memory errors.

**Comment by johnwcowan** [comment]
It sounds like you are re-creating [Typed Racket](https://docs.racket-lang.org/ts-guide/).  But even the Racket people have problems with Typed Racket because of the cost of verifying data as it crosses the border, sometimes repeatedly.  So they are moving in two directions: toward making the whole library Typed Racket, at which point they are truly post-Scheme, and toward simpler, less provable, but more efficient systems like Shallow Typed Racket (which looks only at the top level of a compound object, knowing that it is a List but not what kinds of elements are in it).

The Steme design is different.  First, there are no type annotations except those giving the types of the values returned by a Scheme function to Steme: Steme types are inferred. Since Scheme is dynamically typed, when Steme calls Scheme it can pass arguments of any type, and leave it to Scheme to complain (or not) if they have the wrong types.

By the same token, when Scheme calls Steme, it is up to Scheme to make sure that it calls Steme code with the correct types, as the Steme code may or may not report an error.  Then again, Scheme programs are not required to report dynamic type errors either.  Since all programs have to begin in Scheme (just as in Haskell all programs have to begin in the `IO` monad), this situation is unavoidable, but we learn to live with it.

**Comment by lassik** [comment]
@aijony Gradual typing vs full static typing is the big bet with this project. The latter lacks an `Any` type.

Common Lisp, Typed Racket, Typed Clojure, as well as the JavaScript, Python, and Ruby typing add-ons all went with gradual typing. We decided to be the only dynamic language known to us to take the opposite bet. We feel it suits the simple and clean nature of Scheme to keep the dynamic and static languages separate and make the static language easier to reason about.

This being Scheme, anyone is free to design a gradual typing system. @johnwcowan, @mnieper and I are interested in pursuing full static typing. They would like to design a type system providing many guarantees; I am interested in compatibility with ML family languages, and a fancier type system to the extent that it's not a big issue in translating code. All of us are interested in making the surface syntax similar to Scheme.

**Comment by lassik** [comment]
For now, this repo is about Steme, the name John coined for the language exploring fancier typing.

My original proposal for typed Scheme with ML compatibility was called Statics. Since I'd like to start experimenting with real code at this point, whereas Marc and John are still exploring the design, I'll take the Statics work to [lassik/statics](https://github.com/lassik/statics). Contributors are welcome there as well, especially those who'd like to try writing some ML in Scheme. If the two languages turn out compatible enough, we'll merge them. In any case, we aim to keep the surface syntax and libraries as similar as possible to minimize disruption to the community.

**Comment by mnieper** [comment]
For Steme-Scheme communication, we can have a Datum type, which represents a Scheme datum (and which can be returned by the Scheme reader, for example). Such a Datum type can be fully typed (if the type system is expressive enough, of course) and can be safely constructed and deconstructed by pure Steme code.

This is not the same as an Any type, of which we want to back away, but allows the typing of many seemingly polymorphic Scheme functions.

**Comment by mnieper** [comment]
Can we close this issue?
